package com.edgarchirivella.simpleissuetracker.domain;

import lombok.Getter;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

@Setter
@Getter
@SuperBuilder
@Entity
@Table(name = "bugs")
public class Bug extends Ticket {
    @Column(name = "priority")
    private BugPriority priority;

    @Column(name = "status")
    private BugStatus status;

    // Override constructor generated by @SuperBuilder to set type
    protected Bug(BugBuilder<?, ?> b) {
        super(b);
        this.priority = b.priority;
        this.status = b.status;
        setType(TicketType.BUG);
    }
}
